### ISSUE TITLE
Local embeddings mode requires authentication?

### ISSUE THREAD

**Issue by aivajoe** [arkohut/pensieve#15]
Error:
```
Repository Not Found for url: https://huggingface.co/arkohut/jina-embeddings-v2-base-en/resolve/main/adapter_config.json.
Please make sure you specified the correct `repo_id` and `repo_type`.
If you are trying to access a private or gated repo, make sure you are authenticated.
Invalid username or password.
```

Embeddings config:
```
embedding:
  model: arkohut/jina-embeddings-v2-base-en
  num_dim: 768
  use_local: true
  use_modelscope: false
```
