### ISSUE TITLE
CPU占用持续100% - CPU usage remains at 100%

### ISSUE THREAD

**Issue by rty813** [arkohut/pensieve#44]
目前VLM、OCR我都设置的是非本地部署，通过远程服务器进行计算。理论上本地就只剩下了Embedding，为什么CPU占用率长时间在100%居高不下，这样比较影响实际使用。
![image](https://github.com/user-attachments/assets/85ae024c-e810-4090-927c-ee03626c0711)

附上我的配置文件：
```
base_dir: D:/memos
database_path: database.db
default_library: screenshots
screenshots_dir: screenshots

server_host: 0.0.0.0
server_port: 8839

# Enable authentication by uncommenting the following lines
# auth_username: admin
# auth_password: changeme

default_plugins:
- builtin_ocr
- builtin_vlm

# using ollama as the vlm server
vlm:
  concurrency: 8
  endpoint: http://192.168.3.104:11434
  force_jpeg: true
  modelname: minicpm-v
  prompt: 请帮描述这个图片中的内容，包括画面格局、出现的视觉元素等
  token: ''

# using local ocr
ocr:
  concurrency: 8
  # this is not used if use_local is true
  endpoint: http://192.168.3.104:18000/predict
  force_jpeg: false
  token: ''
  use_local: false

# using local embedding for English as the main language
embedding:
  model: arkohut/jina-embeddings-v2-base-zh
  num_dim: 768
  use_local: true
  use_modelscope: false

# using local embedding for Chinese as the main language
# embedding:
#   model: arkohut/jina-embeddings-v2-base-zh
#   num_dim: 768
#   use_local: true
#   use_modelscope: true

# using ollama embedding
# embedding:
#   endpoint: http://192.168.3.104:11434 # this is not used
#   # model: arkohut/gte-qwen2-1.5b-instruct:q8_0
#   model: qwen2.5:14b-instruct-q8_0
#   num_dim: 1536
#   use_local: false
#   use_modelscope: false

record_interval: 4 # seconds

```
