### ISSUE TITLE
Error upon start 启动时报错

### ISSUE THREAD

**Issue by shiyuwang-jamk** [arkohut/pensieve#52]
### Describe the bug

Anyone may respond in English or Chinese 可以英文或中文回应。

- Python 3.10 with conda enviornment.
- Apple Silicon
- SQLite v 3.45.3, `enable_load_extension is supported`
- Initiation successful.

Output upon `memos start`:
```
╭───────────────────── Traceback (most recent call last) ──────────────────────╮
│ /opt/homebrew/Caskroom/miniconda/base/envs/memos/lib/python3.10/site-package │
│ s/memos/commands.py:634 in start                                             │
│                                                                              │
│   631 │                                                                      │
│   632 │   elif is_macos():                                                   │
│   633 │   │   service_name = "com.user.memos"                                │
│ ❱ 634 │   │   subprocess.run(["launchctl", "start", service_name], check=Tru │
│   635 │   │   typer.echo("Started Memos processes.")                         │
│   636 │   else:                                                              │
│   637 │   │   typer.echo("Unsupported operating system.")                    │
│                                                                              │
│ ╭────────────────────── locals ──────────────────────╮                       │
│ │    memos_dir = PosixPath('[USER ROOT FOLDER]/.memos') │                       │
│ │ service_name = 'com.user.memos'                    │                       │
│ ╰────────────────────────────────────────────────────╯                       │
│                                                                              │
│ /opt/homebrew/Caskroom/miniconda/base/envs/memos/lib/python3.10/subprocess.p │
│ y:526 in run                                                                 │
│                                                                              │
│    523 │   │   │   raise                                                     │
│    524 │   │   retcode = process.poll()                                      │
│    525 │   │   if check and retcode:                                         │
│ ❱  526 │   │   │   raise CalledProcessError(retcode, process.args,           │
│    527 │   │   │   │   │   │   │   │   │    output=stdout, stderr=stderr)    │
│    528 │   return CompletedProcess(process.args, retcode, stdout, stderr)    │
│    529                                                                       │
│                                                                              │
│ ╭───────────────────────────────── locals ─────────────────────────────────╮ │
│ │ capture_output = False                                                   │ │
│ │          check = True                                                    │ │
│ │          input = None                                                    │ │
│ │         kwargs = {}                                                      │ │
│ │      popenargs = (['launchctl', 'start', 'com.user.memos'],)             │ │
│ │        process = <Popen: returncode: 3 args: ['launchctl', 'start',      │ │
│ │                  'com.user.memos']>                                      │ │
│ │        retcode = 3                                                       │ │
│ │         stderr = None                                                    │ │
│ │         stdout = None                                                    │ │
│ │        timeout = None                                                    │ │
│ ╰──────────────────────────────────────────────────────────────────────────╯ │
╰──────────────────────────────────────────────────────────────────────────────╯
CalledProcessError: Command '['launchctl', 'start', 'com.user.memos']' returned
non-zero exit status 3.
```

### Command outputs

Version: `Package: 0.23.2, Python: 3.10.16, System: darwin/arm64`
Config:
```
base_dir:
  value: ~/.memos
  resolved: [USER ROOT FOLDER]/.memos
database_path:
  value: database.db
  resolved: [USER ROOT FOLDER]/.memos/database.db
default_library: screenshots
screenshots_dir:
  value: screenshots
  resolved: [USER ROOT FOLDER]/.memos/screenshots
server_host: 0.0.0.0
server_port: 8839
vlm:
  modelname: minicpm-v
  endpoint: http://localhost:11434
  token: ********
  concurrency: 8
  force_jpeg: True
  prompt: Please describe the content of this image, including the layout and visual elements.
ocr:
  endpoint: http://localhost:5555/predict
  token: ********
  concurrency: 8
  use_local: True
  force_jpeg: False
embedding:
  num_dim: 768
  endpoint: http://localhost:11434/v1/embeddings
  model: arkohut/jina-embeddings-v2-base-en
  use_modelscope: False
  use_local: True
  token: ********
auth_username:
auth_password: ********
default_plugins:
  - builtin_ocr
record_interval: 4
watch:
  rate_window_size: 10
  sparsity_factor: 3.0
  processing_interval: 12
```

### Screenshots or additional context

No log was created in the directory. Only

- `config.yaml`
- `database.db`
