### ISSUE TITLE
[bug?]使用vlm时，ollama内存貌似不能释放

### ISSUE THREAD

**Issue by hcy0317** [arkohut/pensieve#56]
### Describe the bug

在用`memos scan`的时候，发现ollama内存貌似不能释放，不过还没有占满，暂时还没有报错

### Command outputs

```
Package: 0.23.2, Python: 3.10.11, System: windows/amd64
base_dir:
  value: D:/.memos
  resolved: D:\.memos
database_path:
  value: D:/.memos/database.db
  resolved: D:\.memos\database.db
default_library: Dscreenshots
screenshots_dir:
  value: D:/.memos/screenshots
  resolved: D:\.memos\screenshots
server_host: 0.0.0.0
server_port: 8839
vlm:
  modelname: minicpm-v
  endpoint: http://localhost:11434
  token: ********
  concurrency: 8
  force_jpeg: True
  prompt: 请帮描述这个图片中的内容，包括画面格局、出现的视觉元素等
ocr:
  endpoint: http://localhost:5555/predict
  token: ********
  concurrency: 8
  use_local: True
  force_jpeg: False
embedding:
  num_dim: 768
  endpoint: http://localhost:11434/api/embed
  model: arkohut/jina-embeddings-v2-base-zh
  use_modelscope: False
  use_local: True
  token: ********
auth_username:
auth_password: ********
default_plugins:
  - builtin_ocr
  - builtin_vlm
record_interval: 4
watch:
  rate_window_size: 10
  sparsity_factor: 1.0
  processing_interval: 1
```

### Screenshots or additional context

![image](https://github.com/user-attachments/assets/af2d6dbf-09b8-420a-af29-c288ee988edf)
![image](https://github.com/user-attachments/assets/a082f2c2-fa81-4738-8e13-c2f0949035cc)
